### ISSUE TITLE
Required Fanuc Options

### ISSUE THREAD

**Issue by cemcetin** [ABC-iRobotics/fanuc-webcontrol#1]
Hello,

If you could add the required options on the Fanuc controller for this to work, it would be great.

I created a TP file from the ls file, but when putting in the controller, it gives the error "program uses uninstalled options".

Thanks.

**Comment by tarsoly** [comment]
@cemcetin: 
Hello,

What software version is on your robot controller and what is the model of your robot? It also would be good to know what software options are installed on your robot controller.
I try to simulate the scenario and find the solution. 
However, the webmotion.ls TP program can not be work properly without the Karel programs. Perhaps the Karel option is missing on your robot controller.

Best regards,
Sandor
